package com.xiaoyu.erbao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xiaoyu.erbao.DayRecord;

import com.xiaoyu.erbao.DayRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayRecordDaoConfig;

    private final DayRecordDao dayRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayRecordDaoConfig = daoConfigMap.get(DayRecordDao.class).clone();
        dayRecordDaoConfig.initIdentityScope(type);

        dayRecordDao = new DayRecordDao(dayRecordDaoConfig, this);

        registerDao(DayRecord.class, dayRecordDao);
    }
    
    public void clear() {
        dayRecordDaoConfig.getIdentityScope().clear();
    }

    public DayRecordDao getDayRecordDao() {
        return dayRecordDao;
    }

}
