package com.xiaoyu.erbao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig temperatureRecordDaoConfig;
    private final DaoConfig dayRecordDaoConfig;
    private final DaoConfig newsListDaoConfig;
    private final DaoConfig knownledgeListDaoConfig;

    private final TemperatureRecordDao temperatureRecordDao;
    private final DayRecordDao dayRecordDao;
    private final NewsListDao newsListDao;
    private final KnownledgeListDao knownledgeListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        temperatureRecordDaoConfig = daoConfigMap.get(TemperatureRecordDao.class).clone();
        temperatureRecordDaoConfig.initIdentityScope(type);

        dayRecordDaoConfig = daoConfigMap.get(DayRecordDao.class).clone();
        dayRecordDaoConfig.initIdentityScope(type);

        newsListDaoConfig = daoConfigMap.get(NewsListDao.class).clone();
        newsListDaoConfig.initIdentityScope(type);

        knownledgeListDaoConfig = daoConfigMap.get(KnownledgeListDao.class).clone();
        knownledgeListDaoConfig.initIdentityScope(type);

        temperatureRecordDao = new TemperatureRecordDao(temperatureRecordDaoConfig, this);
        dayRecordDao = new DayRecordDao(dayRecordDaoConfig, this);
        newsListDao = new NewsListDao(newsListDaoConfig, this);
        knownledgeListDao = new KnownledgeListDao(knownledgeListDaoConfig, this);

        registerDao(TemperatureRecord.class, temperatureRecordDao);
        registerDao(DayRecord.class, dayRecordDao);
        registerDao(NewsList.class, newsListDao);
        registerDao(KnownledgeList.class, knownledgeListDao);
    }
    
    public void clear() {
        temperatureRecordDaoConfig.getIdentityScope().clear();
        dayRecordDaoConfig.getIdentityScope().clear();
        newsListDaoConfig.getIdentityScope().clear();
        knownledgeListDaoConfig.getIdentityScope().clear();
    }

    public TemperatureRecordDao getTemperatureRecordDao() {
        return temperatureRecordDao;
    }

    public DayRecordDao getDayRecordDao() {
        return dayRecordDao;
    }

    public NewsListDao getNewsListDao() {
        return newsListDao;
    }

    public KnownledgeListDao getKnownledgeListDao() {
        return knownledgeListDao;
    }

}
