package com.xiaoyu.erbao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table KNOWNLEDGE_LIST.
 */
public class KnownledgeList {

    private Integer knownlegeId;
    private String title;
    private String summary;
    private String thumPicUrl;
    private String contentText;
    private String contentUrls;
    private java.util.Date date;
    private Boolean read;
    private String eyes;
    private String favorite;

    public KnownledgeList() {
    }

    public KnownledgeList(Integer knownlegeId) {
        this.knownlegeId = knownlegeId;
    }

    public KnownledgeList(Integer knownlegeId, String title, String summary, String thumPicUrl, String contentText, String contentUrls, java.util.Date date, Boolean read, String eyes, String favorite) {
        this.knownlegeId = knownlegeId;
        this.title = title;
        this.summary = summary;
        this.thumPicUrl = thumPicUrl;
        this.contentText = contentText;
        this.contentUrls = contentUrls;
        this.date = date;
        this.read = read;
        this.eyes = eyes;
        this.favorite = favorite;
    }

    public Integer getKnownlegeId() {
        return knownlegeId;
    }

    public void setKnownlegeId(Integer knownlegeId) {
        this.knownlegeId = knownlegeId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getThumPicUrl() {
        return thumPicUrl;
    }

    public void setThumPicUrl(String thumPicUrl) {
        this.thumPicUrl = thumPicUrl;
    }

    public String getContentText() {
        return contentText;
    }

    public void setContentText(String contentText) {
        this.contentText = contentText;
    }

    public String getContentUrls() {
        return contentUrls;
    }

    public void setContentUrls(String contentUrls) {
        this.contentUrls = contentUrls;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Boolean getRead() {
        return read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    public String getEyes() {
        return eyes;
    }

    public void setEyes(String eyes) {
        this.eyes = eyes;
    }

    public String getFavorite() {
        return favorite;
    }

    public void setFavorite(String favorite) {
        this.favorite = favorite;
    }

}
