package com.xiaoyu.erbao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS_LIST.
 */
public class NewsList {

    private Integer newsId;
    private Integer newsType;
    private String title;
    private String summary;
    private String thumPicUrl;
    private String contentText;
    private String contentUrls;
    private java.util.Date date;
    private Boolean read;
    private String eyes;
    private String says;

    public NewsList() {
    }

    public NewsList(Integer newsId) {
        this.newsId = newsId;
    }

    public NewsList(Integer newsId, Integer newsType, String title, String summary, String thumPicUrl, String contentText, String contentUrls, java.util.Date date, Boolean read, String eyes, String says) {
        this.newsId = newsId;
        this.newsType = newsType;
        this.title = title;
        this.summary = summary;
        this.thumPicUrl = thumPicUrl;
        this.contentText = contentText;
        this.contentUrls = contentUrls;
        this.date = date;
        this.read = read;
        this.eyes = eyes;
        this.says = says;
    }

    public Integer getNewsId() {
        return newsId;
    }

    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    public Integer getNewsType() {
        return newsType;
    }

    public void setNewsType(Integer newsType) {
        this.newsType = newsType;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getThumPicUrl() {
        return thumPicUrl;
    }

    public void setThumPicUrl(String thumPicUrl) {
        this.thumPicUrl = thumPicUrl;
    }

    public String getContentText() {
        return contentText;
    }

    public void setContentText(String contentText) {
        this.contentText = contentText;
    }

    public String getContentUrls() {
        return contentUrls;
    }

    public void setContentUrls(String contentUrls) {
        this.contentUrls = contentUrls;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Boolean getRead() {
        return read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    public String getEyes() {
        return eyes;
    }

    public void setEyes(String eyes) {
        this.eyes = eyes;
    }

    public String getSays() {
        return says;
    }

    public void setSays(String says) {
        this.says = says;
    }

}
