package com.xiaoyu.erbao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEMPERATURE_RECORD.
 */
public class TemperatureRecord {

    private Long date;
    private Integer temperature;

    public TemperatureRecord() {
    }

    public TemperatureRecord(Long date) {
        this.date = date;
    }

    public TemperatureRecord(Long date, Integer temperature) {
        this.date = date;
        this.temperature = temperature;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Integer getTemperature() {
        return temperature;
    }

    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

}
